services:
  db:
    image: "bitnami/postgresql:latest"
    environment:
      - POSTGRESQL_USERNAME=user
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DATABASE=db
    ports:
      - "5432:5432"
